"""empty message

Revision ID: 199fb97490c
Revises: None
Create Date: 2015-08-24 02:29:55.295053

"""

# revision identifiers, used by Alembic.
revision = '199fb97490c'
down_revision = None

from alembic import op
import sqlalchemy as sa
import migration_types


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('met',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('type', migration_types.Enum('rejected', 'accepted', 'notresponsed'), nullable=False),
    sa.Column('A', sa.String(length=50), nullable=True),
    sa.Column('B', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('notice', sa.String(length=200), nullable=True),
    sa.Column('photo_url', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('A', sa.String(length=20), nullable=True),
    sa.Column('B', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_male', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('_height', sa.Integer(), nullable=True),
    sa.Column('is_regular_member', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('graduated_school', sa.String(length=50), nullable=True),
    sa.Column('graduated_school_major', sa.String(length=50), nullable=True),
    sa.Column('job_category', sa.String(length=50), nullable=True),
    sa.Column('job', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('district_meetable', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('characteristic', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=50), nullable=True),
    sa.Column('photo_thumbnail_url', sa.String(length=50), nullable=True),
    sa.Column('phonenum', sa.String(length=20), nullable=True),
    sa.Column('regular_company_email', sa.String(length=50), nullable=True),
    sa.Column('regular_company_id_photo_url', sa.String(length=50), nullable=True),
    sa.Column('regular_company_paper_card_photo_url', sa.String(length=50), nullable=True),
    sa.Column('regular_graduated_school_email', sa.String(length=50), nullable=True),
    sa.Column('regular_graduated_school_id_photo_url', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('phonenum'),
    sa.UniqueConstraint('username')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('requester', sa.String(length=50), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('isDone', sa.Boolean(), nullable=True),
    sa.Column('result_json', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('school_score', sa.Float(), nullable=False),
    sa.Column('work_score', sa.Float(), nullable=False),
    sa.Column('attraction_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=2), nullable=False),
    sa.Column('tierr', migration_types.Enum('aA', 'aB', 'aC', 'bB', 'bC', 'cC'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('self_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=50), nullable=True),
    sa.Column('story', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('isMale', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('female_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('male_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('met__accepted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['met.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('met__not_responsed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['met.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('met__rejected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['met.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('met__rejected')
    op.drop_table('met__not_responsed')
    op.drop_table('met__accepted')
    op.drop_table('male_user')
    op.drop_table('female_user')
    op.drop_table('user')
    op.drop_table('self_story')
    op.drop_table('score')
    op.drop_table('review')
    op.drop_table('response')
    op.drop_table('request')
    op.drop_table('record')
    op.drop_table('progress')
    op.drop_table('phone')
    op.drop_table('notice')
    op.drop_table('met')
    ### end Alembic commands ###
