"""empty message

Revision ID: 1c276b84630
Revises: 
Create Date: 2015-08-24 04:13:35.568596

"""

# revision identifiers, used by Alembic.
revision = '1c276b84630'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from application.models import _external_types


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_score():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('school_score', sa.Float(), nullable=False),
    sa.Column('work_score', sa.Float(), nullable=False),
    sa.Column('attraction_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=2), nullable=False),
    sa.Column('tierr', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade_score():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    ### end Alembic commands ###


def upgrade_file():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_file():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_notice():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_notice():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_progress():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_progress():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_user():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('isMale', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('female_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('male_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_user():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('male_user')
    op.drop_table('female_user')
    op.drop_table('user')
    ### end Alembic commands ###


def upgrade_record():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_male', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('_height', sa.Integer(), nullable=True),
    sa.Column('is_regular_member', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('graduated_school', sa.String(length=50), nullable=True),
    sa.Column('graduated_school_major', sa.String(length=50), nullable=True),
    sa.Column('job_category', sa.String(length=50), nullable=True),
    sa.Column('job', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('district_meetable', sa.String(length=50), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('height', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('characteristic', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=50), nullable=True),
    sa.Column('photo_thumbnail_url', sa.String(length=50), nullable=True),
    sa.Column('phonenum', sa.String(length=20), nullable=True),
    sa.Column('motto', sa.String(length=200), nullable=True),
    sa.Column('regular_company_email', sa.String(length=50), nullable=True),
    sa.Column('regular_company_id_photo_url', sa.String(length=50), nullable=True),
    sa.Column('regular_company_paper_card_photo_url', sa.String(length=50), nullable=True),
    sa.Column('regular_graduated_school_email', sa.String(length=50), nullable=True),
    sa.Column('regular_graduated_school_id_photo_url', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('phonenum'),
    sa.UniqueConstraint('phonenum'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade_record():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    ### end Alembic commands ###


def upgrade_review():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_review():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    ### end Alembic commands ###


def upgrade_selfstory():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_selfstory():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_response():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_response():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_phone():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_phone():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_met():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('met',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.NullType(), nullable=False),
    sa.Column('A', sa.String(length=50), nullable=True),
    sa.Column('B', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('met__accepted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['met.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('met__not_responsed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['met.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('met__rejected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['met.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_met():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('met__rejected')
    op.drop_table('met__not_responsed')
    op.drop_table('met__accepted')
    op.drop_table('met')
    ### end Alembic commands ###


def upgrade_request():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_request():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

