"""empty message

Revision ID: 28561f53072
Revises: None
Create Date: 2015-04-26 03:08:26.618858

"""

# revision identifiers, used by Alembic.
revision = '28561f53072'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
